---
- name: Create group for Node Exporter
  group:
    name: "{{ node_exporter_group }}"
    system: yes

- name: Create user for Node Exporter
  user:
    name: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    system: yes
    shell: "{{ node_exporter_shell }}"
    create_home: no

- name: Set up systemd service
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Enable and start Node Exporter
  systemd:
    name: node_exporter
    state: started
    enabled: true
